apiVersion: v1
kind: ConfigMap
metadata:
  name: a-service
  namespace: practice-helm
data:
  application.yml: |-
    server:
      servlet:
        context-path: /a-path
    spring:
      application:
        name: a-service
      config:
        import: kubernetes
      endpoints:
        bHost: "http://b-service:8081/b-path"
        cHost: "http://c-service:8082/c-path"
    management:
      endpoint:
        health:
          enabled: true
        info:
          enabled: true
        restart:
          enabled: true
