apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
spec:
  rules:
    - host: practice-helm.demo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.server.port }}