image:
  repository: trucnguyen301197
  prefix: helm
service:
  name: a-service
  namespace: practice-helm
  server:
    port: 8080
    servlet:
      contextPath: /a-path
  config:
    import: kubernetes
  endpoints:
    bHost: "http://b-service:8081/b-path"
    cHost: "http://c-service:8082/c-path"
  management:
    endpoint:
      health:
        enabled: true
      info:
        enabled: true
      restart:
        enabled: true

replications:
  desire: 1

