image:
  repository: trucnguyen301197
  prefix: helm
service:
  name: a-service
  namespace: practice-helm
  server:
    port: 80
    servlet:
      contextPath: /a-path
  config:
    import: kubernetes
  endpoints:
    bHost: "http://b-service:80/b-path"
    cHost: "http://c-service:8082/c-path"
  management:
    endpoint:
      health:
        enabled: true
      info:
        enabled: true
      restart:
        enabled: true
  readinessProbe:
    successThreshold: 3
    initialDelaySeconds: 140
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 140
    periodSeconds: 20
    failureThreshold: 3
  restartPolicy: Always

replications:
  desire: 1

