apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-post-install
  labels:
    {{- include "chart.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: pre-install
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo post-install Pod is Running ; sleep 10']
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1